### ISSUE TITLE
Fireplace mode

### ISSUE THREAD

**Issue by pittbull** [GMTrevis/Homeassistant-NodeRed-Systemair-VTR300#8]
Hi again.

I have some issues activating the fireplace mode. This is what's recorded in the debug log when enabling the debug nodes related to "set main modes":

<img width="260" alt="image" src="https://user-images.githubusercontent.com/1532149/197396333-5e2d07e2-b6e1-4786-a017-21150de9206a.png">

Any insight?

**Comment by pittbull** [comment]
It seems that the node "trykkvakt aktiv?" does not change to "fireplace mode" after having being activated a first time. I had to restart NR to get it working, but when the timer runs out on the first time and you try to reactivate it does not change. And the above mentioned node does not change.

**Comment by GMTrevis** [comment]
@pittbull you are correct, found a trykkleif/bug in the following node, this should fix the issue:
![image](https://user-images.githubusercontent.com/69414078/197405911-7f337bb1-06e2-4da7-9138-17ceab55b93e.png)

![image](https://user-images.githubusercontent.com/69414078/197405924-33d9af53-c73d-47f2-98ef-9490c4b1a272.png)

**Comment by pittbull** [comment]
Wow. That is indeed a nice find :) Deeply buried.

Thanks. Confirming the fix works.

**Comment by Ontrackx** [comment]
The workspace contains some nodes that are not properly configured:

[VTR300 - Modbus] Ildsted - Format time (function)
Are you sure you want to deploy?

i get this while changing?

**Comment by GMTrevis** [comment]
@Ontrackx: I saw that myself, i don't have a certain answer for that one but i think it might be related to node red releases/updates. The following solved it for my case:
![image](https://user-images.githubusercontent.com/69414078/197408856-1fba8767-daf4-4a2d-8e6c-daf3575116e0.png)

**Comment by Ontrackx** [comment]
Thanx tht fixed it, i know how to read code somewhat but not to find and correct it :)

**Comment by Ontrackx** [comment]
![Screenshot_2022-10-24-20-09-13-62_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/19576585/197595819-b5985301-279e-4903-a82d-e614b2f8c764.jpg)
This is spamming in logbook all the time, anyone know why?

**Comment by GMTrevis** [comment]
@Ontrackx a lot of code is made outside and in addition to the code running in the ventilation unit. 
When i made this logic there was so many loose threads to put to together including trail and error on the way to make it possible to control the ventilation unit the way i wanted.

So to your question:
Each time a mode is changed are all the other modes turned off, this is checked each 10s (poll cycle) until the ventilation unit respond/the requested mode actually is set (actual feedback). The switch off service is limited to each 30s to reduce service calls. The switch off service calls generate script calls and since HA logs more or less everything, these operations will also be seen. In order to make the ventilation unit user interface with all this buttons (as i wanted), displaying the actual mode (not assumed) i didn't see any other way of solving the control in node red and HA, i also struggled with that the unit not always was setting the requested mode each time, so i had to frequently check the actual state until the new requested mode actually was set. Mixing control of different modbus registers for the different modes including a new mode (PPM Auto) also complicates stuff... The code has potential of being smarter, remembering the previous mode and using that could be an option to reduse the number of scripts beeing called at the same time. As for now i have to put this on hold as i dont have time for a while. please fill free to test and make suggested improvements, highly appreciated later when improving the code for controling the ventilation unit.
